spring:
  datasource:
    url: jdbc:mysql://localhost/devLiquibase
    username: devLiquibase
    password: devLiquibase
    # wait XYZ ms till MySQL Docker container is fully initialized
    hikari:
      initialization-fail-timeout: 30000

  liquibase:
    contexts: migrate-db
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none