version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: devLiquibaseRoot
          MYSQL_DATABASE: devLiquibase
          MYSQL_USER: devLiquibase
          MYSQL_PASSWORD: devLiquibase

    working_directory: ~/spring-liquibase-example

    steps:
      - checkout
      - restore_cache:
          key: spring-liquibase-example-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spring-liquibase-example-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/spring-liquibase-0.0.1-SNAPSHOT.jar